/**
 * Type declarations for the WASM module (generated by wasm-pack).
 *
 * This ambient module declaration provides IDE support and type checking
 * before the WASM package is built. Once `npm run build:wasm` generates
 * `wasm/pkg/`, TypeScript uses the generated types from that directory instead.
 */
declare module "../wasm/pkg/zpl_toolchain_wasm" {
  /** Parse ZPL input and return { ast, diagnostics }. */
  export function parse(input: string): unknown;

  /** Parse ZPL input with explicit parser tables (JSON string). */
  export function parseWithTables(
    input: string,
    tablesJson: string
  ): unknown;

  /** Validate ZPL input with optional printer profile. Returns { ok, issues }. */
  export function validate(
    input: string,
    profileJson?: string
  ): unknown;

  /** Format ZPL input with optional indent style. */
  export function format(input: string, indent?: string): string;

  /** Explain a diagnostic code. Returns the explanation or undefined. */
  export function explain(id: string): string | undefined;
}
