name: Prepare VS Code Core Runtime
description: Build and verify @zpl-toolchain/core runtime artifacts for extension workflows

runs:
  using: composite
  steps:
    - name: Install dependencies, build WASM, and build @zpl-toolchain/core
      shell: bash
      run: |
        cd packages/ts/core
        npm ci
        npm run build:wasm
        npm run build

    - name: Verify core runtime artifacts exist
      shell: bash
      run: |
        test -f packages/ts/core/wasm/pkg/zpl_toolchain_wasm_bg.wasm
        test -f packages/ts/core/dist/index.js
